server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    #不向eureka注册自己
    register-with-eureka: false
    #表示自己是注册中心 维护服务实例 不需要检测服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要的地址
      defaultZone: http://eureka7001.com:7001/eureka/