server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://47.105.180.77:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3307/clouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.guigu.springcloud.entity

eureka:
  client:
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 多节点必须设置为true 并配合ribbon使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # EurekaServer的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    #是否展示ip
    prefer-ip-address: true
    #客户端多久向服务端  发送一次心跳  签约时间
    lease-renewal-interval-in-seconds: 1
    #服务端至少多久要接受客户端一次心跳 否则断开 以最后一次接受到的心跳为起点  服务到期后 续约时间
    lease-expiration-duration-in-seconds: 20
