server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 多节点必须设置为true 并配合ribbon使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # EurekaServer的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80